import createFetchClient from "openapi-fetch";
import type { Middleware } from "openapi-fetch";
import type { paths } from "~/consts/schema"; // generated by openapi-typescript

// const baseUrl = "https://api.realworld.show/api";
const baseUrl = process.env.NEXT_PUBLIC_API_ENDPOINT

export const fetchClient = createFetchClient<paths>({ baseUrl });

const myMiddleware: Middleware = {
    async onRequest({ request, options }) {
        // make compatibale for the client side
        // const token = typeof window === 'undefined' ? await getSession() : await fetch("http://localhost:3000/api/get-token").then(res => res.json()).then(res => res.data)
        // const token = await getSession()
        const token = ''
        if (token) {
            request.headers.set("Authorization", `Token ${token}`);
        }
        return request;
    },
    async onResponse({ request, response, options }) {
        // const { body, ...resOptions } = response.clone();
        // console.log(resOptions)
        // // change status of response
        // return new Response(body, { ...resOptions, status: resOptions.status || 400 });

        return response.clone()
    },
    async onError({ error }) {
        return new Error("Oops, fetch failed", { cause: error });
        // wrap errors thrown by fetch
        // onError({ error }) {
        //     return new Error("Oops, fetch failed", { cause: error });
        // },
    },
};

fetchClient.use(myMiddleware)

export default fetchClient;
